# Uploads a snapshot release
#
# Triggered by 
# Push new game code (stored in game/core)
# Manual Trigger
#

name: Generate snapshot release

on:
  push:
    branches:
      - main
    paths:
      - game/core/**
  workflow_dispatch:

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17 # Perhaps not needed on ubuntu-24
        uses: actions/setup-java@v2
        with: 
          java-version: 17
          distribution: "temurin"

      - name: Build and test
        run: |
          cd game
          chmod +x gradlew 
          ./gradlew clean build jacocoTestReport
      
      - name: Make jar executable
        run: chmod +x game/lwjgl3/build/libs/*.jar
      
      - name: Get current date
        id: date
        run: python3 "game/_devUtils/generate_release_date.py" # TODO - fix release tag clashes

      - run: echo "-> ${{ steps.date.outputs.date }}"
      
      - name: Zip artifact
        run: |
          cd game/lwjgl3/build
          ls -la
          zip -r Longboi-life-snapshot-${{ steps.date.outputs.date }}.zip libs
      
      - name: Get last commit message
        id: last_commit_message
        run: echo "LAST_COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")" >> $GITHUB_ENV

      - name: Create release
        id: create_release
        uses: comnoco/create-release-action@7dea6dc82ac9d97ced7a764aa82811451bba80e0 # v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # provided by actions
        with:
          tag_name: snapshot-${{ steps.date.outputs.date}}
          release_name: snapshot-${{ steps.date.outputs.date }}
          draft: false
          prerelease: true
          body: |
            PreRelease Version, stability not guaranteed
            ${{ steps.last_commit_message.outputs.LAST_COMMIT_MESSAGE }}

      - name: Upload release asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: game/lwjgl3/build/Longboi-life-snapshot-${{ steps.date.outputs.date }}.zip
          asset_name: Longboi-life-snapshot-${{ steps.date.outputs.date }}.zip
          asset_content_type: application/zip
        